app: sykepengesoknad-andre-inntektskilder-logikk-test
namespace: flex
team: flex
kafkaPool: nav-prod
azureTenant: nav.no
env:
  SYKEPENGESOKNAD_BACKEND_AAD_CLIENT_ID: prod-gcp.flex.sykepengesoknad-backend
